apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: delete-replicaset
  namespace: p-spring-delete
  labels:
    app: delete-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-product
  template:
    metadata:
      labels:
        app: delete-product
    spec:
      nodeSelector:
        workload: update
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: update
          image: alejandro411/p_spring_delete:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: maria-delete-secret
